

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing Sentry CLI via Actions test
    steps:
      - name: Send Release to Sentry
        uses: dmandrade/sentry-release-github-action@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: liz 
          SENTRY_PROJECT: round-robin
        with:
          version: test-dmandrade-release-action
