on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing Sentry CLI via Actions test
    steps:
    - name: Hello world action step
      uses: LearningNerd/ga-sentry-test@master
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: liz
        SENTRY_PROJECT: round-robin
      with:
        environment: 'testingga'
    # Use the output from the `hello` step
    - name: Last step
      run: echo "hi"
